// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxtjaecyisojmrkubyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54dGphZWN5aXNvam1ya3VieWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDgyMjMsImV4cCI6MjA2MTM4NDIyM30.wt_K0Cg7Xr5i_HQKToNGFjQ3gZFNKLhFhN1BU8vmWEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);